name: landcover-unet

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - cookiecutter
  - jupyterlab
  - nodejs
  - pip
  - python
  - python-dotenv
  - pip:
    - azure-storage-blob
    - boto3
    - pyarrow
